### ISSUE TITLE
Laravel Packages

### ISSUE THREAD

**Issue by twocngdagz** [mattstauffer/Torch#55]
Is there a way to use Laravel Packages in Torch?

**Comment by mattstauffer** [comment]
Can you explain your question more?

**Comment by twocngdagz** [comment]
I mean, if for example, I used a laravel package you usually install on app.php and add to the service provider. Would you able to achieve this also in Torch?

**Comment by mattstauffer** [comment]
Ah. Torch isn't a tool or a framework. Torch is basically instructional blog posts in code form. It's just showing you how to use these components elsewhere.

It would be near impossible to give a high level instruction for how to import any Laravel package in a non-Laravel app, because each package uses different hooks into Laravel's core.

Hope this helps.

**Comment by twocngdagz** [comment]
Ahh, thank you very much for this information

**Comment by mattstauffer** [comment]
You're welcome! Enjoy!
