### ISSUE TITLE
Set the request session

### ISSUE THREAD

**Issue by drjoju** [mattstauffer/Torch#61]
Hello,

I'm trying to flash the request variables. Something like

`$request->flash();
`
Previously in my code I created the $request like
`$request = Illuminate\Http\Request::createFromGlobals();
`
 The error is:
Fatal error: Uncaught exception 'RuntimeException' with message 'Session store not set on request.'

I create the session object following the instructions in the page:

https://github.com/mattstauffer/Torch/blob/master/components/session/index.php 

The questión is.

How can assign the session to the request? 

The idea is to use the variables back to fill the input fill in a form in case of error.

Thanks and best regards

**Comment by mattstauffer** [comment]
@drjoju Great question!

Here's the code that sets the session on the request:

https://github.com/laravel/framework/blob/5f4cd45d8137f1cadb9e0e4ac7270a3b637f5781/src/Illuminate/Session/Middleware/StartSession.php#L48-L75

So you can probably figure it out from there--seems you need to run `$request->setLaravelSession($your session here)`. 

Sessions are a bit difficult because you also sometimes have to do some work with them after the request is over, which you can also see in that code.

I don't have time to learn it and share it here, but if you do end up figuring it out, please share here. Thanks!
