### ISSUE TITLE
Named Routes

### ISSUE THREAD

**Issue by iarafat** [mattstauffer/Torch#64]
How to use and echo named routes? In routing component.

**Comment by AkenRoberts** [comment]
Hi @themeyellow! Could you clarify how exactly you want to use named routes? That can make it easier for people to guide you. Thanks :)

**Comment by SL0wZEr** [comment]
@mattstauffer I'm working on this at the moment, and I want your opinion, here's what I did: 

After Instantiating new `UrlGenerator` object: 

```
$url = new UrlGenerator($router->getRoutes(), $request);
```

I can now get the URL to a named route like this `$url->route('Torch');`, but the problem is the route must be registered like this - using `as` not `name`: 

```
$router->get('/', ['as' => 'users.index', 'uses' => 'UsersController@index']);
```

If we want to use `name` instead of `as` there are two **options**: 

1. Set the `name` before the HTTP verb

``` 
$router->name('users.index')->get('/', 'UsersController@index');
```

2. Add `refreshNameLookups()` and `refreshActionLookups()` at the end of `routes.php` as done in Laravel's `RouteServiceProvider`

```
$router->getRoutes()->refreshNameLookups();
$router->getRoutes()->refreshActionLookups();
```

What do you suggest?

**Comment by mattstauffer** [comment]
@SL0wZEr Huh, really good point.

What if we have one route that works without the refresh and one that doesn't? The default route can be `as`

**Comment by rhsanet** [comment]
some could please explain me why this $router->get('/teste', 'TesteRouterController@index'); does not work but if insede $router->group(['namespace' => 'App\Controller', 'prefix' => ''], function (Router $router) { ... works? Error:
Fatal error: Uncaught ReflectionException: Class TesteRouterController does not exist in C:\Users\users\Desktop\medb-sistema\vendor\illuminate\container\Container.php:752 Stack trace: #0 C:\Users\users\Desktop\medb-sistema\vendor\illuminate\container\Container.php(752): ReflectionClass->__construct('TesteRouterCont...') #1 C:\Users\users\Desktop\medb-sistema\vendor\illuminate\container\Container.php(631): Illuminate\Container\Container->build('TesteRouterCont...') #2 C:\Users\users\Desktop\medb-sistema\vendor\illuminate\container\Container.php(586): Illuminate\Container\Container->resolve('TesteRouterCont...', Array) #3 C:\Users\users\Desktop\medb-sistema\vendor\illuminate\routing\Route.php(226): Illuminate\Container\Container->make('TesteRouterCont...') #4 C:\Users\users\Desktop\medb-sistema\vendor\illuminate\routing\Route.php(796): Illuminate\Routing\Route->getController() #5 C:\Users\users\Desktop\medb-sistema\vendor\illuminate\routing\Route.php(757): Illuminate\Routing\Route->controllerMiddleware() #6 C:\Users\users\D in C:\Users\users\Desktop\medb-sistema\vendor\illuminate\container\Container.php on line 752

**Comment by AkenRoberts** [comment]
When you specify a controller in the route, in your case `TesteRouterController`, you want it to be the fully-qualified class name, which is the class with its full namespace. If your controller's namespace is `App\Controller`, then the route definition should be:

```php
$router->get('/teste', 'App\Controller\TesteRouterController@index');
```

The `$router->group()` with the namespace definition is basically a way to shortcut this, so you don't need to always used the fully-qualified name with every route. It's useful if they all share the same namespace, so you don't have to type it over and over.

Laravel adds in the default controller namespace for you when you use the framework, which is why this seems transparent - it's doing the `$router->group()` call for you.
